### ISSUE TITLE
Personal Dimensional door client disconnect/crash

### ISSUE THREAD

**Issue by chaoskagami** [CannibalVox/DimDoors#12]
Steps to reproduce: Enter personal dimensional door. Place another Personal Dimensional Door inside this dimension. Break the door just placed. Use rift eraser on generated rift. Client will be disconnected, but not full-out crash to launcher. Server doesn't crash. I couldn't get a backtrace, but it should be reproducible.

P.S.
Thank you for continuing this mod. It's one of my favorites. I would have forward ported it myself from the 1.6.4 version had you not. ;)

**Comment by chaoskagami** [comment]
Also, the exits behave oddly and link together, so it's impossible to exit the personal dimension without a /tpx 0

**Comment by CannibalVox** [comment]
Fixed both with  https://github.com/CannibalVox/DimDoors/commit/44a0d4b3ec4f06b1e2405ff15572ab931506282e
