### ISSUE TITLE
Crash while logging out of minecraft while in a dim door

### ISSUE THREAD

**Issue by crunkazcanbe** [CannibalVox/DimDoors#14]
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at StevenDimDoors.mod_pocketDim.world.PocketProvider.func_76556_a(PocketProvider.java:92)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:45)
	at net.minecraft.world.World.<init>(World.java:244)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by CannibalVox** [comment]
get me the entire log please

**Comment by crunkazcanbe** [comment]
Sorry about that man here you go http://pastebin.com/VyddVn8F

I was just trying to make it eaiser on you by giving you the most relevant information .

BTW I really appreciate it that you brought this old mod back. :)

Thank you

-Crunk

**Comment by CannibalVox** [comment]
I believe this was fixed in 91f96c825c22598167cd288a6a76eb8957cc4bcb.  I'm going to release a test7 and please reopen this if it's not fixed.

**Comment by keenerb** [comment]
Sorry canvox, but when I left the dimension:

```
[B#283]  [13:18:20] [Client thread/FATAL]: Unreported exception thrown!
[B#283]  java.lang.IllegalArgumentException: Could not get provider type for dimension 3, does not exist
[B#283]  	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148) ~[DimensionManager.class:?]
[B#283]  	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302) ~[DimensionManager.class:?]
[B#283]  	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160) ~[aqo.class:?]
[B#283]  	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54) ~[bjf.class:?]
[B#283]  	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:865) ~[bjb.class:?]
[B#283]  	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32) ~[hs.class:?]
[B#283]  	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13) ~[hs.class:?]
[B#283]  	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[B#283]  	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) ~[bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
[B#283]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[B#283]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
[B#283]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[B#283]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[B#283]  [13:18:20] [Client thread/INFO] [STDOUT]: 
```

**Comment by crunkazcanbe** [comment]
Look here man https://imgur.com/eqceaOb are those spots in the creative tab supposed to be blank item images ? When you hover over it there are things there , but you can not see it though . Btw beta 7 fixed the issue I was having . No more crashing while logging out of mc in a dim door . :)

**Comment by DPxKnightxZero** [comment]
Question Keenreb what other mods do you have installed? I tested Canibal Voxes New Release and I have a 182 mods and no crashing ...

**Comment by crunkazcanbe** [comment]
Ok man thanx . It's this dern texture pack and i don't know why . Btw running real smooth man 304 mods installed and no problems yet. Im loving this

**Comment by DPxKnightxZero** [comment]
Check Out My Server We have world guard :D http://bitly.com/DPGDLSF You need this to play share it with friends.

**Comment by DPxKnightxZero** [comment]
Only legit accounts can connect to server.
