### ISSUE TITLE
Personal Dimensional Doors Erase On Entry?

### ISSUE THREAD

**Issue by DPxKnightxZero** [CannibalVox/DimDoors#15]
Okay Zer0 here, so I was testing the mod as much as possible for you vox and the only issue I can see is if someone places a personal dimensional pocket dimension (the white room as I call it.) and you let someone else enter it erases all items and changes ... I am not sure what could be causing this. Does not happen with any other  type of dimensional door.

**Comment by CannibalVox** [comment]
Fixed in 2.2.5-test8
