### ISSUE TITLE
Incorrect lighting in sub-personal-dimension on server restart

### ISSUE THREAD

**Issue by chaoskagami** [CannibalVox/DimDoors#18]
Time for another report. Steps to reproduce: Place personal dimensional door. Enter. Place dimensional door. Enter. Logout, restart server, log in. Result looks like this when it should be 100% white like previous. Also, my client minimap seems to show the dimension with a black outer color on reload vs white: 

![2015-03-20_18 00 58](https://cloud.githubusercontent.com/assets/7855098/6757746/b651e6ca-cf09-11e4-8169-5d9ea69f2136.png)

Again, like the previous issue I reported, this only occurs on a server. Not on a client opened to LAN. There's also nothing in the log for this one since it's rendering-related. This has been tested sans every other mod as well, so feel free to ignore the other stuff in my inventory.

EDIT: Also, running on test8. Forgot that.

**Comment by DPxKnightxZero** [comment]
I will see if I can verify this bug.

**Comment by CannibalVox** [comment]
Looks like a bug that used to happen where the personal was sometimes using the basic pocket provider client-side, causing the lighting to be jacked up.  I'll investigate this.

**Comment by chaoskagami** [comment]
It only seems to happen on a server, and only specifically in secondary personal dimensions. The main one is always lit correctly after a server restart. It also lights correctly until a server restart, including client connect and disconnect, entering, exiting, etc.

Anyways, it's only visual. It's not going to eat my world. Lower priority, I'd say.

**Comment by chaoskagami** [comment]
If investigation of this isn't going anywhere, mind if I have a look on my end? If I can figure it out, I'll submit a pull request with a fix.

I have a lot of time, anyways.

**Comment by CannibalVox** [comment]
Hi, I'm trying to understand this bug- when I place a personal door inside my personal dimension, the door sends me to limbo, which is what's supposed to happen.  Is that not the case for you?

**Comment by chaoskagami** [comment]
This bug has nothing to do with personal doors in personal dimensions. That works correct - you get sent to limbo.

I'm talking about placing normal dimensional doors in personal dimensions. It is completely fine with colors (black), unless running a server and the server is restarted. After which the normally-black dimension takes on the odd lighting in the screenshot.

This only happens in a forge server. It doesn't happen with singleplayer or open-to-LAN. I couldn't figure out what was causing it, and I'm unsure if it still happens. I can test it again, if you'd like.
