### ISSUE TITLE
Enemy Spawn In Dimensional Doors 

### ISSUE THREAD

**Issue by DPxKnightxZero** [CannibalVox/DimDoors#19]
Okay I noticed now enemies are spawning in the dimensional doors and in crazy amounts. I am using test8 this didn't happen in test 7

**Comment by DPxKnightxZero** [comment]
My own stupidty

**Comment by Revemohl** [comment]
Out of curiosity, how did you get this to happen? Biome ID conflicts?

**Comment by DPxKnightxZero** [comment]
Okay I covered all the flooring and re-moved the ambiance black lighting.
