### ISSUE TITLE
A option in config

### ISSUE THREAD

**Issue by crunkazcanbe** [CannibalVox/DimDoors#20]
A option in the config to change the rarity the doors ore spawned in the overworld would be nice .

**Comment by NotGyro** [comment]
I'm pretty sure that the Gateway Generation Chance option is exactly this, though it could be something else.

```
    # Sets the chance (out of 10000) that a Rift Gateway will generate in a given chunk. The default chance is 15.
    I:"Gateway Generation Chance"=15
```

**Comment by CannibalVox** [comment]
NotGyro is correct.
