### ISSUE TITLE
[bug][Crash] changing worlds

### ISSUE THREAD

**Issue by AnimeniacYuuto** [CannibalVox/DimDoors#29]
Hey I am getting a crash when switching worlds while using this mod. Crash log: https://www.dropbox.com/s/m3ym8kw097l3m0d/latest.log?dl=0

It may be worth noting that both of the worlds involved are super flat worlds generated without dimensional doors.

p.s. also I am planning to use this update in Jampacked 2 if that's okay?

**Comment by DPxKnightxZero** [comment]
Can I please get the log located in the crash log folder?

**Comment by AnimeniacYuuto** [comment]
https://www.dropbox.com/s/vfsf1l5pfo1z64t/crash-2015-04-09_17.50.20-server.txt?dl=0 theres a crash log, and no I have not used this on a server yet

**Comment by CannibalVox** [comment]
These logs are gone now, so I'm going to close this.
