### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AaronSutter** [CannibalVox/DimDoors#35]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/17/15 10:10 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at StevenDimDoors.mod_pocketDim.core.PocketManager.createAndRegisterBlacklist(PocketManager.java:715)
	at StevenDimDoors.mod_pocketDim.saving.DDSaveHandler.loadAll(DDSaveHandler.java:59)
	at StevenDimDoors.mod_pocketDim.core.PocketManager.loadInternal(PocketManager.java:390)
	at StevenDimDoors.mod_pocketDim.core.PocketManager.load(PocketManager.java:192)
	at StevenDimDoors.mod_pocketDim.EventHookContainer.onWorldLoad(EventHookContainer.java:124)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_265_EventHookContainer_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 834485272 bytes (795 MB) / 1807200256 bytes (1723 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.138.1400 Minecraft Forge 10.13.3.1400 112 mods loaded, 111 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.138.1400} [Forge Mod Loader] (forge-1.7.10-10.13.3.1400-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.3.1400} [Minecraft Forge] (forge-1.7.10-10.13.3.1400-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Pistronics2{0.5.1} [Pistronics 2] (1.7.10-Pistronics2-v0.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AnimationAPI{1.2.3} [AnimationAPI] (AnimationAPI-1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	aether{Alpha 1.7.10-1.4} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AetherAspects{Alpha 1.7.10-1.2} [Aether Aspects] (AetherAspects-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AgriCraft{1.7.10-1.4.0-alpha-4} [AgriCraft] (AgriCraft-1.7.10-1.4.0-alpha-4-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Artifacts{1.1.2} [Artifacts] (Artifacts-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	asielib{0.2.7} [asielib] (AsieLib-1.7.10-0.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Automagy{0.26} [Automagy] (Automagy-1.7.10-0.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1283-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BloodArsenal{1.1-14} [Blood Arsenal] (BloodArsenal 1.1-14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BloodUtils{1.4} [BloodUtils] (BloodUtils-1.4_B0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bluepower{0.2.954} [Blue Power] (BluePower-1.7.10-0.2.954-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Botania{r1.7-201} [Botania] (Botania r1.7-201.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	dimdoors{2.2.5-test} [Dimensional Doors] (DimensionalDoors-2.2.5-test8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ec3toprojecte{1.0} [ec3toprojecte] (EssentialCraftv4.5.1710.223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	essentialcraft{4.5.1710.223} [Essential Craft 3] (EssentialCraftv4.5.1710.223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	essenthaum{1.1.1710.0} [Essential Thaumaturgy] (EssentialThaumaturgy-1.1.1710.11EC(4.4.1710.37)TC(4.2.3.5).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	farseek{1.0.8} [Farseek] (Farseek-1.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GardenOfGlass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff-1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff-1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff-1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff-1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	HardcoreEnderExpansion{1.8.2} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	imc{1.6} [Improving Minecraft] (Improving Minecraft-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	LookingGlass{0.0.1.01} [Looking Glass] (lookingglass-1.7.10-0.0.1.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.7.10-1.3.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.10-1.3.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mystcraft{0.11.10.00} [Mystcraft] (mystcraft-1.7.10-0.11.10.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	runicdungeons{1.1.4} [Runic Dungeons] (runicdungeons-1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-31.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	streams{0.1.4} [Streams] (Streams-0.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TaintedMagic{1.1.5.4} [Tainted Magic] (TaintedMagic-1.1.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Talismans 2{1.1.6} [Talismans 2] (Talismans2-1.7.10-1.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	thaumicbases{1.0.1710.8} [Thaumic Bases] (ThaumicBases1.0.1710.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-52.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TravellersGear{1.16.5} [Traveller's Gear] (TravellersGear-1.7.10-1.16.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TWarden{1.1.1} [Thaumic Warden] (TWarden-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ubcores{1.7.10-0.2.3.0} [UBC Ore Registrar] (UBCOres-1.7.10-0.2.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WarpTheory{1.7.10R1.0} [WarpTheory] (WarpTheory-1.7-1.0-24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.0.8.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DPxKnightxZero** [comment]
Which version are you using?

**Comment by Soyaro666** [comment]
crashlog says dimdoors{2.2.5-test}. or is the log missing something?

**Comment by AaronSutter** [comment]
The log says 2.2.5 test but the version that I've been using, and which caused this crash is version 2.2.6 test 8. I am playing a 100+ modpack though I didn't run into this issue until after entering a dim door and save/quitting. Every time I load up the world with the mod installed I get this crah. Without it installed the world loads fine. Tried reinstalling mod after loading the world once without it and same crash.

**Comment by CannibalVox** [comment]
Did you ever use the command /dd-resetdungeons?

**Comment by AaronSutter** [comment]
No, most complex thing I've done is use the rift remover in LAN server mode
