### ISSUE TITLE
Crash when passing through Dimensional Door (already inside)

### ISSUE THREAD

**Issue by ajthemacboy** [CannibalVox/DimDoors#45]
Here's the crash report: http://pastebin.com/5jdnGaWW

The pack is a custom modpack, and the mod is up to date. This is a crash report from a player. 

By the way, thanks for updating this mod.. it's one of my favourites, I have lots of great memories with it :)

Edit: Here's another report: http://pastebin.com/DVxMDRNW

**Comment by P3rf3ctXZer0** [comment]
Can I please get the full crash report all logs etc? This isn't enough to figure out the issue. Also can you please use this tool and print your modlist to text? http://users.adam.com.au/paulwh/_Pages/dirprint.html

**Comment by P3rf3ctXZer0** [comment]
I stand corrected please remove aether and gilded games utils. Some issue with gilded games utils cause issues in my modpack with a similar crash.

**Comment by ajthemacboy** [comment]
Aether is very buggy, I know, but I probably won't remove it from my pack. If there's nothing you can do I'll understand and deal with the occasional crash.

**Comment by P3rf3ctXZer0** [comment]
Sounds good. Please close this comment and make sure you let the aether team know about the gilded games issues.

**Comment by ajthemacboy** [comment]
Will do!
