### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by kurokuno** [CannibalVox/DimDoors#7]
sorry about the lack of a full log will drop it in a new comment so it updates the issue =P

**Comment by CannibalVox** [comment]
I need the entire crash log.

**Comment by kurokuno** [comment]
http://pastebin.com/TAT7zML1 full crash log for you

**Comment by CannibalVox** [comment]
You have the first release still, I've released 4 since then. :-P https://github.com/CannibalVox/DimDoors/releases

**Comment by CannibalVox** [comment]
Turns out I can't even read!  Sorry.

**Comment by CannibalVox** [comment]
Apologies again for the premature close.  This issue is now fixed in the test6 release.

**Comment by kurokuno** [comment]
no need to be sorry =P and thanks for fixing this so super fast <3
