### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by DarTau** [CannibalVox/DimDoors#8]
I don't know, if it's a bug or not, but "Personal dimensional door" and "Golden dimensional door" have the same crafting recipe (2 golden doors + stable fabric), so I cannot craft one of them.
Is it ok, that Monoliths are no more just eyes flying in the air, but the eyes on a black background, that looks like a real monolith?
Oh, yea, and the Monoliths open their eyes too fast. In 1.6.4 I could run away, now it's really hard.

**Comment by keenerb** [comment]
Dimdoors added a quartz door I noticed.  I expect that should be in the personal door recipe...

**Comment by CannibalVox** [comment]
It is a bug, I've checked in a fix.  I made monoliths look like monoliths again, I like them better that way and am I jerk who's changing steven's vision :-P

As for how fast monoliths open their eyes, they open them very fast if they are configured not to teleport you (and they don't teleport you in limbo by default).  If they're opening their eyes quickly and also teleporting you, that's a problem (for certain values of "quickly").  Let us know how fast we're talking and whether they teleport you.

**Comment by DarTau** [comment]
It takes about 5 secs to open the eye and teleport. Visually, it's twice faster, than in 1.6.4 (visually, but not sure... already forgot the 1.6.4, but as I remember, there was about 8-10 secs)

**Comment by DarTau** [comment]
Oh, I see.
In Limbo the eyes open as usual (if docile monoliths in config file set to false), but in pocket dimensions (using spawn monoliths) or in dimensional mazes it's twice faster.

**Comment by CannibalVox** [comment]
That seems backwards, I'll check it out, thanks!

**Comment by DarTau** [comment]
Some more strange behaviour of monoliths.
I checked, that limbo's monoliths open long enough (about 50-60 secs), so I spawned there a monolith from an egg. After that some monoliths began to open fast (about 12-20 secs), and some monoliths were still opening slow (50-60 secs).
Also, after this, I had a bug with 1 sec opening and teleportation in dimensional mazes.
Checked twice in different worlds.

**Comment by DarTau** [comment]
Also, is that ok, that I got teleportated, when I try to hit a Monolith?

**Comment by DarTau** [comment]
I mean, the Monoliths become full activated, when they are hit. Arrow shot from a long range doesn't seem to teleport me.

**Comment by CannibalVox** [comment]
It looks like there is code here to instantly teleport players who attack the monolith, which seems OK to me.

As for the teleport speed, SenseiKiwi changed the logic in the way monoliths "charge up" so it makes sense that it'd be a little different.  I'll figure out how fast they used to charge on average & go back to that speed.

test6 was just released and includes fixes for the personal doors recipe

**Comment by CannibalVox** [comment]
Hi, when you compare the code to 1.6.4, which version are you referring to?

**Comment by DarTau** [comment]
Mm, is it really ok with teleportation on hit?
I mean, if you want to destroy any block in Limbo and occasionally hit the Monolith, it will teleport you, though you didn't really want to hit 'em.
In Limbo it takes 1-2 secs for an eye of Monolith to appear, so something like that could really happen.
Also it will become hard to run away the teleportation, if some players want to shoot you.
They shoot - shot to the nearby monolith - bzzzhhyuum.

Ermm, is the previous post for me? If it is..
Truly, I don't compare the code, as I don't understand anything in it, so I'm comparing the game process)
I used a "DimensionalDoors-2.2.2RC1-295-kiwi" version

**Comment by CannibalVox** [comment]
That's what I needed to know, thank you.  I'll give some thought to this.  I appreciate your input!

**Comment by codebracker** [comment]
Actually the Monoliths charge faster in a dimDungeon because they are placed there so players can't just mine out of a maze with no drawbacks, it's intentional. It also didn't use to be a problem since you could see their eyes trough walls, so you knew you shouldn't dig trough walls there.
And if they are charging faster in pocket dimensions, that shouldn't be a problem because they don't spawn there.
Teleportation on hit is explained that they are usually sleeping, so if anyone hits them they wake up/charge instantly. Though this seems a bit unfair in SMP it fits with the lore. Maybe there could be a way to make them look at the player who actually hit them instead of the closest one?
No idea how you accidentally hit a Monolith while mining, but they do seem to have a tendency to clip trough terain, maybe making their hitbox just their eye woud be a good idea?
