### ISSUE TITLE
Portal texture broken on Dimensional Trapdoors

### ISSUE THREAD

**Issue by nanakisan** [CannibalVox/DimDoors#9]
https://i.imgur.com/gBCuoEk.png

Currently using v2.2.5-T6-RE

**Comment by CannibalVox** [comment]
http://puu.sh/gCfeu/89cd48259d.jpg

Unable to reproduce, can you give me more info about your system?

**Comment by nanakisan** [comment]
Strange the only thing I can tell you is that my instances use 
Java 7 (tested with J8 and still same issue)
forge 10.13.2.1307
LGPL 2.9.1

Another odd thing is that the white overlay in my image. It is moving 1 pixel south-east every tick.

**Comment by keenerb** [comment]
Are you running optifine?

**Comment by nanakisan** [comment]
Nope no optifine. This is a straight up test instance. I even disabled all my mods.

**Comment by CannibalVox** [comment]
I mean your computer, can you give me information about it?

**Comment by nanakisan** [comment]
It's a old pile of crap so prepare to snort milk
AMD Phenom-II X2 3.0 ghz
AMD Radeon Mobility 4250
500gb HDD
4gb DDR3 ram

**Comment by keenerb** [comment]
I can't duplicate either on multiple servers.  Possibly video card driver issue?

**Comment by CannibalVox** [comment]
Probably an AMD is trash issue.  Oh ho ho ho ho.

**Comment by DPxKnightxZero** [comment]
AMD is far from trash ... I am a technician and intel is simply overpriced amd. Its nothing special but I don't expect many people to understand that.

**Comment by CannibalVox** [comment]
That's cool, but realtalk it sounds like your computer can't handle the weird stuff we do to render the portal effect.  I'm going to recommend you turn off portal rendering and remind myself to act on #3 soon.

**Comment by nanakisan** [comment]
If I have issue rendering portals. Why is it normal doors from the mod render just fine? No offense CanVox but don't outright diss someones machine like that. how was I supposed to know this was a 1 time thing special to my computer? I live and breath testing mods for stuff like this. I'm not upset i'm just a bit disappointed you responded like that.

**Comment by DPxKnightxZero** [comment]
Your graphics card is outdated (made in 2010) I recommend you replace it because I am not having rendering issues. Also I understand his frustration ... he just wants things to work and sometimes people working take out their irritation on others. It wasn't personal I am sure.

**Comment by nanakisan** [comment]
Kinda hard to replace gpu on a laptop my friend. hahahah but thanks for the words of comfort.
